
FROM python:3.10-slim
WORKDIR /app

RUN apt-get update
RUN apt-get -yy install bart

COPY scripts/ /app/

RUN pip install numpy==1.26.4 scipy==1.10.1 matplotlib==3.7.1 mrd-python==2.0.0 

CMD ["python3"]

